language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install -g react-native-cli
  - npm install -g detox-cli
script:
  - npm ci
  - npx jest --ci
  - npm run e2e:ci
